(function () {
  "use strict";
  var rows = [], threshold = 0, resizeTimer = null, showEnthalpy = false, hoverIndex = null, geometry = null;
  function byId(id){ return document.getElementById(id); }
  var canvas=byId("plot"), status=byId("status"), startEl=byId("start"), endEl=byId("end"), loadBtn=byId("load"), saveBtn=byId("save"), summary=byId("summary"), subtitle=byId("subtitle"), enthalpyToggle=byId("enthalpyToggle"), tooltip=byId("tooltip"), enthalpyLegend=byId("enthalpyLegend");
  function pad(v){return String(v).padStart(2,"0");}
  function roundToHour(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate(),d.getHours(),0,0,0);}
  function addHours(d,h){return new Date(d.getTime()+h*3600000);}
  function toInputValue(d){return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate())+"T"+pad(d.getHours())+":00";}
  function toDateValue(d){return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate());}
  function parseTime(v){var m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3],+m[4],+m[5],0,0):null;}
  function showStatus(t,type){status.textContent=t;status.className="status "+type;}
  function saturationPressure(t){return 6.112*Math.exp(17.62*t/(243.12+t));}
  function mixingRatio(dp,p){var e=saturationPressure(dp);return 622*e/Math.max(p-e,0.000001);}
  function moistAirEnthalpy(t,g){var x=g/1000;return 1.006*t+x*(2501+1.86*t);}
  function median(a){a=a.filter(Number.isFinite).slice().sort(function(x,y){return x-y;});if(!a.length)return 1013.25;var m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
  function calculateThreshold(p){var e=.40*saturationPressure(22);return 622*e/Math.max(p-e,.000001);}
  function parseResponse(data,source){if(!data.hourly||!Array.isArray(data.hourly.time)||!Array.isArray(data.hourly.temperature_2m)||!Array.isArray(data.hourly.dew_point_2m)||!Array.isArray(data.hourly.surface_pressure))throw new Error(source+": unvollständige Stundenwerte");var n=Math.min(data.hourly.time.length,data.hourly.temperature_2m.length,data.hourly.dew_point_2m.length,data.hourly.surface_pressure.length),out=[];for(var i=0;i<n;i++){var time=parseTime(data.hourly.time[i]),t=Number(data.hourly.temperature_2m[i]),dp=Number(data.hourly.dew_point_2m[i]),p=Number(data.hourly.surface_pressure[i]);if(!time||![t,dp,p].every(Number.isFinite))continue;var h=mixingRatio(dp,p);out.push({time:time,temp:t,pressure:p,humidity:h,enthalpy:moistAirEnthalpy(t,h),source:source});}return out;}
  function fetchRows(url,source){return fetch(url,{cache:"no-store"}).then(function(r){return r.text().then(function(body){if(!r.ok)throw new Error(source+": HTTP "+r.status+" - "+body.slice(0,160));try{return parseResponse(JSON.parse(body),source);}catch(e){if(e.message.indexOf(source)===0)throw e;throw new Error(source+": Antwort war kein gültiges JSON");}});});}
  function requestRecentAndFuture(start,end){var now=roundToHour(new Date()),past=Math.min(Math.max(0,Math.ceil((now-start)/86400000))+1,14),future=Math.min(Math.max(1,Math.ceil((end-now)/86400000)+1),16);return fetchRows("https://api.open-meteo.com/v1/forecast?latitude=51.1328&longitude=13.7672&hourly=temperature_2m,dew_point_2m,surface_pressure&timezone=Europe%2FBerlin&past_days="+past+"&forecast_days="+future,"Aktuelle Wetterdaten");}
  function requestArchive(start,end){return fetchRows("https://archive-api.open-meteo.com/v1/archive?latitude=51.1328&longitude=13.7672&hourly=temperature_2m,dew_point_2m,surface_pressure&timezone=Europe%2FBerlin&start_date="+toDateValue(start)+"&end_date="+toDateValue(end),"Historische Wetterdaten");}
  function validateRange(s,e){if(!s||!e)throw new Error("Bitte Anfang und Ende auswählen.");if(e<=s)throw new Error("Das Ende muss nach dem Anfang liegen.");if(e-s>14*86400000)throw new Error("Der Zeitraum darf maximal 14 Tage betragen.");}
  function updateCurrentCards(){if(!rows.length)return;var now=Date.now(),best=rows.reduce(function(a,b){return Math.abs(b.time-now)<Math.abs(a.time-now)?b:a;});byId("currentTemp").textContent=best.temp.toFixed(1)+" °C";byId("currentHumidity").textContent=best.humidity.toFixed(1)+" g/kg";byId("currentEnthalpy").textContent=best.enthalpy.toFixed(1)+" kJ/kg";byId("currentTime").textContent=best.time.toLocaleString("de-DE",{weekday:"short",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});}
  function loadRange(){var start=parseTime(startEl.value),end=parseTime(endEl.value);try{validateRange(start,end);}catch(e){showStatus(e.message,"error");return;}showStatus("Wetterdaten werden geladen ...","loading");loadBtn.disabled=true;saveBtn.disabled=true;var now=roundToHour(new Date()),boundary=addHours(now,-14*24),jobs=[];if(start<boundary)jobs.push(requestArchive(start,end<boundary?end:addHours(boundary,-1)));if(end>=boundary)jobs.push(requestRecentAndFuture(start>boundary?start:boundary,end));Promise.all(jobs).then(function(parts){var map={};parts.forEach(function(part){part.forEach(function(r){map[r.time.getTime()]=r;});});rows=Object.keys(map).map(function(k){return map[k];}).filter(function(r){return r.time>=start&&r.time<=end;}).sort(function(a,b){return a.time-b.time;});if(!rows.length)throw new Error("Keine Daten im gewählten Zeitraum gefunden.");threshold=calculateThreshold(median(rows.map(function(r){return r.pressure;})));summary.textContent=rows.length+" Stundenwerte | Grenzwert "+threshold.toFixed(1)+" g/kg";subtitle.textContent=start.toLocaleString("de-DE")+" bis "+end.toLocaleString("de-DE");updateCurrentCards();draw();saveBtn.disabled=false;showStatus("Daten erfolgreich geladen.","success");}).catch(function(e){console.error(e);showStatus("Fehler: "+e.message,"error");}).finally(function(){loadBtn.disabled=false;});}
  function draw(){if(!rows.length)return;var box=canvas.parentElement,w=Math.max(box.clientWidth,320),h=Math.max(box.clientHeight,420),ratio=window.devicePixelRatio||1;canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio);canvas.style.width=w+"px";canvas.style.height=h+"px";var c=canvas.getContext("2d");c.setTransform(ratio,0,0,ratio,0,0);c.fillStyle="#fff";c.fillRect(0,0,w,h);var margin={left:62,right:showEnthalpy?132:72,top:28,bottom:82},pw=w-margin.left-margin.right,ph=h-margin.top-margin.bottom,temps=rows.map(function(r){return r.temp;}),hums=rows.map(function(r){return r.humidity;}),enths=rows.map(function(r){return r.enthalpy;}),tMin=Math.floor(Math.min.apply(null,temps)-1),tMax=Math.ceil(Math.max.apply(null,temps)+1),hMin=Math.max(0,Math.floor(Math.min.apply(null,hums.concat([threshold]))-.5)),hMax=Math.ceil(Math.max.apply(null,hums.concat([threshold]))+.5),eMin=Math.floor(Math.min.apply(null,enths)-2),eMax=Math.ceil(Math.max.apply(null,enths)+2);if(tMin===tMax)tMax++;if(hMin===hMax)hMax++;if(eMin===eMax)eMax++;function x(i){return margin.left+i/Math.max(rows.length-1,1)*pw;}function y(v,min,max){return margin.top+(max-v)/(max-min)*ph;}geometry={left:margin.left,right:margin.left+pw,top:margin.top,bottom:margin.top+ph,width:pw,height:ph,x:x};c.font="12px Arial";for(var s=0;s<=6;s++){var f=s/6,yy=margin.top+f*ph;c.strokeStyle="rgba(0,0,0,.11)";c.beginPath();c.moveTo(margin.left,yy);c.lineTo(margin.left+pw,yy);c.stroke();c.textAlign="right";c.fillStyle="#9b1c1c";c.fillText((tMax-f*(tMax-tMin)).toFixed(1),margin.left-8,yy+4);c.textAlign="left";c.fillStyle="#16823b";c.fillText((hMax-f*(hMax-hMin)).toFixed(1),margin.left+pw+8,yy+4);if(showEnthalpy){c.fillStyle="#6f42c1";c.fillText((eMax-f*(eMax-eMin)).toFixed(1),margin.left+pw+65,yy+4);}}
    rows.forEach(function(r,i){var hr=r.time.getHours();if([0,6,12,18].indexOf(hr)<0)return;c.strokeStyle=hr===0?"rgba(0,0,0,.42)":"rgba(0,0,0,.12)";c.setLineDash(hr===0?[]:[3,5]);c.beginPath();c.moveTo(x(i),margin.top);c.lineTo(x(i),margin.top+ph);c.stroke();});c.setLineDash([]);
    function line(vals,min,max,color){c.strokeStyle=color;c.lineWidth=2.4;c.beginPath();vals.forEach(function(v,i){if(i)c.lineTo(x(i),y(v,min,max));else c.moveTo(x(i),y(v,min,max));});c.stroke();}line(temps,tMin,tMax,"#9b1c1c");line(hums,hMin,hMax,"#16823b");if(showEnthalpy)line(enths,eMin,eMax,"#6f42c1");c.strokeStyle="#e02020";c.setLineDash([8,6]);c.beginPath();c.moveTo(margin.left,y(threshold,hMin,hMax));c.lineTo(margin.left+pw,y(threshold,hMin,hMax));c.stroke();c.setLineDash([]);c.strokeStyle="#555";c.strokeRect(margin.left,margin.top,pw,ph);
    var last="";rows.forEach(function(r,i){var key=toDateValue(r.time);if(key===last)return;last=key;c.fillStyle=(r.time.getDay()===0||r.time.getDay()===6)?"#9b1c1c":"#222";c.textAlign="center";c.font=rows.length>240?"bold 10px Arial":"bold 11px Arial";c.fillText(r.time.toLocaleDateString("de-DE",{weekday:"short",day:"2-digit",month:"2-digit"}),x(i),margin.top+ph+43);});c.font="12px Arial";c.fillStyle="#444";c.textAlign="center";c.fillText("Ortszeit Dresden",margin.left+pw/2,h-12);
    if(hoverIndex!==null&&rows[hoverIndex]){var hx=x(hoverIndex);c.strokeStyle="#111";c.lineWidth=1;c.setLineDash([4,4]);c.beginPath();c.moveTo(hx,margin.top);c.lineTo(hx,margin.top+ph);c.stroke();c.setLineDash([]);[[rows[hoverIndex].temp,tMin,tMax,"#9b1c1c"],[rows[hoverIndex].humidity,hMin,hMax,"#16823b"]].concat(showEnthalpy?[[rows[hoverIndex].enthalpy,eMin,eMax,"#6f42c1"]]:[]).forEach(function(p){c.fillStyle=p[3];c.beginPath();c.arc(hx,y(p[0],p[1],p[2]),4,0,Math.PI*2);c.fill();});}}
  function pointerMove(ev){if(!geometry||!rows.length)return;var rect=canvas.getBoundingClientRect(),px=(ev.touches?ev.touches[0].clientX:ev.clientX)-rect.left;if(px<geometry.left||px>geometry.right){pointerLeave();return;}hoverIndex=Math.max(0,Math.min(rows.length-1,Math.round((px-geometry.left)/geometry.width*(rows.length-1))));var r=rows[hoverIndex];tooltip.innerHTML="<strong>"+r.time.toLocaleString("de-DE")+"</strong><br>Temperatur: "+r.temp.toFixed(1)+" °C<br>Absolute Feuchte: "+r.humidity.toFixed(1)+" g/kg"+(showEnthalpy?"<br>Enthalpie: "+r.enthalpy.toFixed(1)+" kJ/kg":"");tooltip.style.display="block";var left=Math.min(Math.max(px+12,6),rect.width-tooltip.offsetWidth-6),py=(ev.touches?ev.touches[0].clientY:ev.clientY)-rect.top;tooltip.style.left=left+"px";tooltip.style.top=Math.max(6,Math.min(py-tooltip.offsetHeight-12,rect.height-tooltip.offsetHeight-6))+"px";draw();}
  function pointerLeave(){hoverIndex=null;tooltip.style.display="none";draw();}
  function quickRange(hours,past){var now=roundToHour(new Date());startEl.value=toInputValue(past?addHours(now,-hours):now);endEl.value=toInputValue(past?now:addHours(now,hours));loadRange();}
  enthalpyToggle.addEventListener("change",function(){showEnthalpy=this.checked;enthalpyLegend.hidden=!showEnthalpy;draw();});loadBtn.addEventListener("click",loadRange);saveBtn.addEventListener("click",function(){var a=document.createElement("a");a.download="wetterplot-dresden.png";a.href=canvas.toDataURL("image/png");a.click();});document.querySelectorAll("[data-hours]").forEach(function(b){b.addEventListener("click",function(){quickRange(Number(b.getAttribute("data-hours")),b.getAttribute("data-past")==="1");});});canvas.addEventListener("mousemove",pointerMove);canvas.addEventListener("mouseleave",pointerLeave);canvas.addEventListener("touchmove",function(e){e.preventDefault();pointerMove(e);},{passive:false});canvas.addEventListener("touchend",pointerLeave);window.addEventListener("resize",function(){clearTimeout(resizeTimer);resizeTimer=setTimeout(draw,150);});var now=roundToHour(new Date());startEl.value=toInputValue(now);endEl.value=toInputValue(addHours(now,168));showStatus("JavaScript funktioniert. Wetterdaten werden geladen ...","loading");loadRange();
})();