(function () {
  "use strict";
  var rows = [], threshold = 0;
  var $ = function (id) { return document.getElementById(id); };
  var canvas = $("plot"), status = $("status"), startEl = $("start"), endEl = $("end"), loadBtn = $("load"), saveBtn = $("save");
  function pad(n){ return String(n).padStart(2,"0"); }
  function hour(d){ return new Date(d.getFullYear(),d.getMonth(),d.getDate(),d.getHours(),0,0,0); }
  function addHours(d,h){ return new Date(d.getTime()+h*3600000); }
  function inputValue(d){ return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate())+"T"+pad(d.getHours())+":00"; }
  function dateValue(d){ return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate()); }
  function parseTime(s){ var m=String(s).match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/); return m?new Date(+m[1],+m[2]-1,+m[3],+m[4],+m[5]):null; }
  function sat(t){ return 6.112*Math.exp(17.62*t/(243.12+t)); }
  function mix(td,p){ var e=sat(td); return 622*e/Math.max(p-e,0.000001); }
  function median(a){ a=a.slice().sort(function(x,y){return x-y;}); var m=Math.floor(a.length/2); return a.length%2?a[m]:(a[m-1]+a[m])/2; }
  function setStatus(text,type){ status.textContent=text; status.className="status "+type; }
  function url(base,a,b){ return base+"?latitude=51.1328&longitude=13.7672&hourly=temperature_2m,dew_point_2m,surface_pressure&timezone=Europe%2FBerlin&start_date="+dateValue(a)+"&end_date="+dateValue(b); }
  function fetchRows(api,source){ return fetch(api).then(function(r){if(!r.ok)throw new Error(source+": HTTP "+r.status);return r.json();}).then(function(d){if(!d.hourly)throw new Error(source+": keine Stundenwerte");return d.hourly.time.map(function(t,i){var dt=parseTime(t),temp=Number(d.hourly.temperature_2m[i]),dew=Number(d.hourly.dew_point_2m[i]),p=Number(d.hourly.surface_pressure[i]);return {time:dt,temp:temp,p:p,hum:mix(dew,p),source:source};}).filter(function(r){return r.time&&Number.isFinite(r.temp)&&Number.isFinite(r.p)&&Number.isFinite(r.hum);});}); }
  function load(){ var a=parseTime(startEl.value),b=parseTime(endEl.value); if(!a||!b||b<=a){setStatus("Bitte gültigen Anfang und Ende wählen.","error");return;} if((b-a)>14*86400000){setStatus("Maximal 14 Tage sind erlaubt.","error");return;} setStatus("Wetterdaten werden geladen ...","loading"); loadBtn.disabled=true; saveBtn.disabled=true; var today=new Date(); today=new Date(today.getFullYear(),today.getMonth(),today.getDate()); var jobs=[]; if(a<today){var pe=b<today?b:addHours(today,-1);jobs.push(fetchRows(url("https://historical-forecast-api.open-meteo.com/v1/forecast",a,pe),"Historie"));} if(b>=today){var fs=a>today?a:today;jobs.push(fetchRows(url("https://api.open-meteo.com/v1/forecast",fs,b),"Vorhersage"));} Promise.all(jobs).then(function(parts){var map={};parts.forEach(function(part){part.forEach(function(r){map[r.time.getTime()]=r;});});rows=Object.keys(map).map(function(k){return map[k];}).filter(function(r){return r.time>=a&&r.time<=b;}).sort(function(x,y){return x.time-y.time;});if(!rows.length)throw new Error("Keine Daten im gewählten Zeitraum.");var pmed=median(rows.map(function(r){return r.p;}));var e=.4*sat(22);threshold=622*e/(pmed-e);$("summary").textContent=rows.length+" Stundenwerte | Grenzwert "+threshold.toFixed(1)+" g/kg";$("subtitle").textContent=a.toLocaleString("de-DE")+" bis "+b.toLocaleString("de-DE");draw();saveBtn.disabled=false;setStatus("Daten erfolgreich geladen.","success");}).catch(function(e){setStatus("Fehler: "+e.message,"error");}).finally(function(){loadBtn.disabled=false;}); }
  function draw(){ var box=canvas.parentElement,w=Math.max(box.clientWidth,320),h=Math.max(box.clientHeight,420),dpr=window.devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+"px";canvas.style.height=h+"px";var c=canvas.getContext("2d");c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle="#fff";c.fillRect(0,0,w,h);var m={l:65,r:70,t:30,b:85},pw=w-m.l-m.r,ph=h-m.t-m.b;var ts=rows.map(function(r){return r.temp;}),hs=rows.map(function(r){return r.hum;});var t0=Math.floor(Math.min.apply(null,ts)-1),t1=Math.ceil(Math.max.apply(null,ts)+1),h0=Math.max(0,Math.floor(Math.min.apply(null,hs.concat([threshold]))-.5)),h1=Math.ceil(Math.max.apply(null,hs.concat([threshold]))+.5);function x(i){return m.l+i/Math.max(rows.length-1,1)*pw;}function yt(v){return m.t+(t1-v)/(t1-t0)*ph;}function yh(v){return m.t+(h1-v)/(h1-h0)*ph;}c.font="12px Arial";for(var j=0;j<=6;j++){var f=j/6,y=m.t+f*ph;c.strokeStyle="rgba(0,0,0,.12)";c.beginPath();c.moveTo(m.l,y);c.lineTo(m.l+pw,y);c.stroke();c.fillStyle="#8b0000";c.textAlign="right";c.fillText((t1-f*(t1-t0)).toFixed(1),m.l-8,y+4);c.fillStyle="#16823b";c.textAlign="left";c.fillText((h1-f*(h1-h0)).toFixed(1),m.l+pw+8,y+4);} rows.forEach(function(r,i){var hr=r.time.getHours();if(hr===0||hr===6||hr===12||hr===18){c.strokeStyle=hr===0?"rgba(0,0,0,.5)":"rgba(0,0,0,.15)";c.setLineDash(hr===0?[]:[3,5]);c.beginPath();c.moveTo(x(i),m.t);c.lineTo(x(i),m.t+ph);c.stroke();if(hr!==0||rows.length<200){c.setLineDash([]);c.fillStyle="#555";c.textAlign="center";c.fillText(pad(hr)+":00",x(i),m.t+ph+18);}}});c.setLineDash([]);function line(vals,y,color){c.strokeStyle=color;c.lineWidth=2;c.beginPath();vals.forEach(function(v,i){if(i)c.lineTo(x(i),y(v));else c.moveTo(x(i),y(v));});c.stroke();}line(ts,yt,"#8b0000");line(hs,yh,"#16823b");c.strokeStyle="#e02020";c.setLineDash([8,6]);c.beginPath();c.moveTo(m.l,yh(threshold));c.lineTo(m.l+pw,yh(threshold));c.stroke();c.setLineDash([]);c.strokeStyle="#555";c.strokeRect(m.l,m.t,pw,ph);var last="";rows.forEach(function(r,i){var key=dateValue(r.time);if(key!==last){last=key;c.fillStyle=(r.time.getDay()===0||r.time.getDay()===6)?"#8b0000":"#222";c.textAlign="center";c.font="bold 11px Arial";c.fillText(r.time.toLocaleDateString("de-DE",{weekday:"short",day:"2-digit",month:"2-digit"}),x(i),m.t+ph+48);}});c.font="12px Arial";c.fillStyle="#444";c.textAlign="center";c.fillText("Ortszeit Dresden",m.l+pw/2,h-12); }
  function quick(hours,past){var n=hour(new Date()),a=past?addHours(n,-hours):n,b=past?n:addHours(n,hours);startEl.value=inputValue(a);endEl.value=inputValue(b);load();}
  loadBtn.addEventListener("click",load);saveBtn.addEventListener("click",function(){var a=document.createElement("a");a.download="wetterplot-dresden.png";a.href=canvas.toDataURL("image/png");a.click();});document.querySelectorAll("[data-hours]").forEach(function(b){b.addEventListener("click",function(){quick(Number(b.getAttribute("data-hours")),b.getAttribute("data-past")==="1");});});window.addEventListener("resize",function(){if(rows.length)draw();});var n=hour(new Date());startEl.value=inputValue(n);endEl.value=inputValue(addHours(n,168));setStatus("JavaScript funktioniert. Wetterdaten werden geladen ...","loading");load();
})();
